Config.Outfits = {
    ['RED'] = {
        male = {
            ['tshirt_1'] = 15, ['tshirt_2'] = 0,
            ['torso_1'] = 12, ['torso_2'] = 0,
            ['arms'] = 1, ['arms_2'] = 0,
            ['pants_1'] = 6, ['pants_2'] = 0,
            ['shoes_1'] = 7, ['shoes_2'] = 0,
            ['bproof_1'] = 0, ['bproof_2'] = 0,
            ['helmet_1'] = -1, ['helmet_2'] = 0,
            ['bags_1'] = 0, ['bags_2'] = 0,
        },
        female = {
            ['tshirt_1'] = 15, ['tshirt_2'] = 0,
            ['torso_1'] = 5, ['torso_2'] = 0,
            ['arms'] = 1, ['arms_2'] = 0,
            ['pants_1'] = 3, ['pants_2'] = 0,
            ['shoes_1'] = 3, ['shoes_2'] = 0,
            ['bproof_1'] = 0, ['bproof_2'] = 0,
            ['helmet_1'] = -1, ['helmet_2'] = 0,
            ['bags_1'] = 0, ['bags_2'] = 0,
        },
    },
    ['BLUE'] = {
        male = {
            ['tshirt_1'] = 15, ['tshirt_2'] = 0,
            ['torso_1'] = 12, ['torso_2'] = 2,
            ['arms'] = 1, ['arms_2'] = 0,
            ['pants_1'] = 6, ['pants_2'] = 2,
            ['shoes_1'] = 7, ['shoes_2'] = 0,
            ['bproof_1'] = 0, ['bproof_2'] = 0,
            ['helmet_1'] = -1, ['helmet_2'] = 0,
            ['bags_1'] = 0, ['bags_2'] = 0,
        },
        female = {
            ['tshirt_1'] = 15, ['tshirt_2'] = 0,
            ['torso_1'] = 5, ['torso_2'] = 2,
            ['arms'] = 1, ['arms_2'] = 0,
            ['pants_1'] = 3, ['pants_2'] = 2,
            ['shoes_1'] = 3, ['shoes_2'] = 0,
            ['bproof_1'] = 0, ['bproof_2'] = 0,
            ['helmet_1'] = -1, ['helmet_2'] = 0,
            ['bags_1'] = 0, ['bags_2'] = 0,
        },
    },
    ['GREEN'] = {
        male = {
            ['tshirt_1'] = 15, ['tshirt_2'] = 0,
            ['torso_1'] = 12, ['torso_2'] = 4,
            ['arms'] = 1, ['arms_2'] = 0,
            ['pants_1'] = 6, ['pants_2'] = 4,
            ['shoes_1'] = 7, ['shoes_2'] = 0,
            ['bproof_1'] = 0, ['bproof_2'] = 0,
            ['helmet_1'] = -1, ['helmet_2'] = 0,
            ['bags_1'] = 0, ['bags_2'] = 0,
        },
        female = {
            ['tshirt_1'] = 15, ['tshirt_2'] = 0,
            ['torso_1'] = 5, ['torso_2'] = 4,
            ['arms'] = 1, ['arms_2'] = 0,
            ['pants_1'] = 3, ['pants_2'] = 4,
            ['shoes_1'] = 3, ['shoes_2'] = 0,
            ['bproof_1'] = 0, ['bproof_2'] = 0,
            ['helmet_1'] = -1, ['helmet_2'] = 0,
            ['bags_1'] = 0, ['bags_2'] = 0,
        },
    },
    ['BLACK'] = {
        male = {
            ['tshirt_1'] = 15, ['tshirt_2'] = 0,
            ['torso_1'] = 12, ['torso_2'] = 1,
            ['arms'] = 1, ['arms_2'] = 0,
            ['pants_1'] = 6, ['pants_2'] = 1,
            ['shoes_1'] = 7, ['shoes_2'] = 0,
            ['bproof_1'] = 0, ['bproof_2'] = 0,
            ['helmet_1'] = -1, ['helmet_2'] = 0,
            ['bags_1'] = 0, ['bags_2'] = 0,
        },
        female = {
            ['tshirt_1'] = 15, ['tshirt_2'] = 0,
            ['torso_1'] = 5, ['torso_2'] = 1,
            ['arms'] = 1, ['arms_2'] = 0,
            ['pants_1'] = 3, ['pants_2'] = 1,
            ['shoes_1'] = 3, ['shoes_2'] = 0,
            ['bproof_1'] = 0, ['bproof_2'] = 0,
            ['helmet_1'] = -1, ['helmet_2'] = 0,
            ['bags_1'] = 0, ['bags_2'] = 0,
        },
    },
}
